# Generated by Django 4.2.3 on 2023-09-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdname', models.CharField(max_length=100)),
                ('stdid', models.IntegerField(primary_key=True, serialize=False)),
                ('scname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
